--- 
_init_setup_model: true
batch_size: 1024
n_steps: 256
learning_rate: 0.0003
clip_range: 0.2
clip_range_vf: null
create_eval_env: false
device: auto
ent_coef: 0.02
gae_lambda: 0.975
gamma: 0.99
max_grad_norm: 0.5
n_epochs: 10
sde_sample_freq: -1
seed: null
target_kl: null
tensorboard_log: null
use_sde: false
verbose: 2
vf_coef: 0.5
