---
learning_rate: 0.0003
buffer_size: 1000000
learning_starts: 50000
batch_size: 512
tau: 0.005
gamma: 0.99
train_freq: 64
gradient_steps: 256
action_noise: null
optimize_memory_usage: False
ent_coef: "auto_0.25"
target_update_interval: 1
target_entropy: -150
use_sde: False
sde_sample_freq: -1
use_sde_at_warmup: False
tensorboard_log: null
create_eval_env: False
verbose: 0
seed: null
device: "cuda"
_init_setup_model: True